name: ci
on: pull_request

# Secrets:
#   SONAR_ORGANIZATION - sonarcloud organization key
#   SONAR_PROJECTKEY   - sonarcloud organization key
#   SONAR_TOKEN        - sonarcloud security token

jobs:
        
  Setup:
  # Try to load dependecies from cache, install dependecies on cache miss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}
      
      - name: Setup scala
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: olafurpg/setup-scala@v10
        with:
         java-version: adopt@1.11
          
      - name: Initialize project
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: "sbt initialize"
                
  Test:
    runs-on: ubuntu-latest
    needs: [Setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup scala
        uses: olafurpg/setup-scala@v10
        with:
         java-version: adopt@1.11
        
      - name: Restore cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}
                  
      - name: Run tests
        run: "sbt test"
        
  Build_image:
    runs-on: ubuntu-latest
    needs: [Setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup scala
        uses: olafurpg/setup-scala@v10
        with:
         java-version: adopt@1.11
        
      - name: Restore cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}
          
      - name: Build docker image
        run: sbt docker
        
  Static_analysis:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        with:
          args: >
            -Dsonar.verbose=true
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
